// frameworks/sveltekit/ts/src/lib/pages/MagazineModePage.svelte
<script lang="ts">
import type NutrientViewer from "@nutrient-sdk/viewer";
import { onDestroy, onMount } from "svelte";
import {
  loadMagazineViewer,
  unloadMagazineViewer,
} from "../examples/magazine-mode/implementation";
import { loadNutrientViewer } from "../utils/loadNutrientViewer";

let container: HTMLDivElement;
let nutrientViewer: typeof NutrientViewer | null = null;

onMount(async () => {
  if (!container) return;

  try {
    nutrientViewer = loadNutrientViewer();

    loadMagazineViewer(nutrientViewer, container);
  } catch (error) {
    console.error("Failed to load Nutrient Viewer:", error);
  }
});

onDestroy(() => {
  if (nutrientViewer && container) {
    unloadMagazineViewer(nutrientViewer, container);
  }
});

function goBack() {
  window.history.back();
}
</script>

<div class="page">
  <nav class="nav">
    <button on:click={goBack} class="back-link">
      ← Back to Examples
    </button>
    <h2 class="title">Basic Viewer</h2>
    <span class="description">
      Simple PDF viewing with standard controls
    </span>
  </nav>

  <div 
    bind:this={container} 
    class="container"
  />
</div>

<style>
  .page {
    height: 100vh;
    display: flex;
    flex-direction: column;
  }

  .nav {
    padding: 1rem;
    background-color: #f5f5f5;
    border-bottom: 1px solid #ddd;
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .back-link {
    background: none;
    border: none;
    color: #4A8FED;
    font-size: 0.9rem;
    cursor: pointer;
    text-decoration: none;
  }

  .back-link:hover {
    text-decoration: underline;
  }

  .title {
    margin: 0;
    font-size: 1.1rem;
  }

  .description {
    font-size: 0.9rem;
    color: #666;
  }

  .container {
    flex: 1;
    width: 100%;
    position: relative;
    min-height: 400px;
  }
</style>

// frameworks/vue/TS/src/pages/MagazineModePage.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import {
  loadMagazineViewer,
  unloadMagazineViewer,
} from "../examples/magazine-mode/implementation";
import { loadNutrientViewer } from "../utils/loadNutrientViewer";

const containerRef = ref<HTMLDivElement | null>(null);

let nutrientViewer: Awaited<ReturnType<typeof loadNutrientViewer>> | null =
  null;

onMounted(async () => {
  const container = containerRef.value;

  if (!container) return;

  try {
    nutrientViewer = await loadNutrientViewer();

    nutrientViewer.unload(container);

    loadMagazineViewer(nutrientViewer, container);
  } catch (error) {
    console.error("Failed to load Nutrient Viewer:", error);
  }

  return () => {
    if (nutrientViewer && container) {
      unloadMagazineViewer(nutrientViewer, container);
    }
  };
});

onUnmounted(() => {
  const container = containerRef.value;
  const { NutrientViewer } = window;

  if (container && NutrientViewer) {
    unloadMagazineViewer(NutrientViewer, container);
  }
});
</script>

<template>
  <div :style="{ height: '100vh', display: 'flex', flexDirection: 'column' }">
    <nav
      :style="{
        padding: '1rem',
        backgroundColor: '#f5f5f5',
        borderBottom: '1px solid #ddd',
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
      }"
    >
      <router-link
        to="/"
        :style="{
          textDecoration: 'none',
          color: '#4A8FED',
          fontSize: '0.9rem',
        }"
      >
        ← Back to Examples
      </router-link>
      <h2 :style="{ margin: 0, fontSize: '1.1rem' }">Magazine Mode</h2>
      <span :style="{ fontSize: '0.9rem', color: '#666' }">
        Double-page layout with custom toolbar and fullscreen support
      </span>
    </nav>

    <div ref="containerRef" :style="{ flex: 1, width: '100%' }" />
  </div>
</template>
