// frameworks/svelte/JS/src/pages/CustomOverlaysPage.svelte
<script>
import { onDestroy, onMount } from "svelte";
import {
  loadCustomOverlaysViewer,
  unloadCustomOverlaysViewer,
} from "../examples/custom-overlays/implementation";
import { loadNutrientViewer } from "../utils/loadNutrientViewer";

const container = null;
let nutrientViewer = null;

onMount(async () => {
  if (!container) return;

  try {
    nutrientViewer = loadNutrientViewer();

    loadCustomOverlaysViewer(nutrientViewer, container);
  } catch (error) {
    console.error("Failed to load Nutrient Viewer:", error);
  }
});

onDestroy(() => {
  if (nutrientViewer && container) {
    unloadCustomOverlaysViewer(nutrientViewer, container);
  }
});

function goBack() {
  window.history.back();
}
</script>

<div class="page">
  <nav class="nav">
    <button on:click={goBack} class="back-link">
      ← Back to Examples
    </button>
    <h2 class="title">Basic Viewer</h2>
    <span class="description">
      Simple PDF viewing with standard controls
    </span>
  </nav>

  <div 
    bind:this={container} 
    class="container"
  />
</div>

<style>
  .page {
    height: 100vh;
    display: flex;
    flex-direction: column;
  }

  .nav {
    padding: 1rem;
    background-color: #f5f5f5;
    border-bottom: 1px solid #ddd;
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .back-link {
    background: none;
    border: none;
    color: #4A8FED;
    font-size: 0.9rem;
    cursor: pointer;
    text-decoration: none;
  }

  .back-link:hover {
    text-decoration: underline;
  }

  .title {
    margin: 0;
    font-size: 1.1rem;
  }

  .description {
    font-size: 0.9rem;
    color: #666;
  }

  .container {
    flex: 1;
    width: 100%;
    position: relative;
    min-height: 400px;
  }
</style>

// frameworks/react/JS/src/pages/CustomOverlaysPage.jsx
import { useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import {
  loadCustomOverlaysViewer,
  unloadCustomOverlaysViewer,
} from "../examples/custom-overlays/implementation";
import { loadNutrientViewer } from "../utils/loadNutrientViewer";

function CustomOverlaysPage() {
  const containerRef = useRef(null);

  useEffect(() => {
    const container = containerRef.current;

    if (!container) return;

    let nutrientViewer;

    try {
      nutrientViewer = loadNutrientViewer();

      loadCustomOverlaysViewer(nutrientViewer, container);
    } catch (error) {
      console.error("Failed to load Nutrient Viewer:", error);
    }

    return () => {
      if (nutrientViewer && container) {
        unloadCustomOverlaysViewer(nutrientViewer, container);
      }
    };
  }, []);

  return (
    <div style={{ height: "100vh", display: "flex", flexDirection: "column" }}>
      <nav
        style={{
          padding: "1rem",
          backgroundColor: "#f5f5f5",
          borderBottom: "1px solid #ddd",
          display: "flex",
          alignItems: "center",
          gap: "1rem",
        }}
      >
        <Link
          to="/"
          style={{
            textDecoration: "none",
            color: "#4A8FED",
            fontSize: "0.9rem",
          }}
        >
          ← Back to Examples
        </Link>
        <h2 style={{ margin: 0, fontSize: "1.1rem" }}>Custom Overlays</h2>
        <span style={{ fontSize: "0.9rem", color: "#666" }}>
          Interactive overlays that appear on page clicks
        </span>
      </nav>

      <div ref={containerRef} style={{ flex: 1, width: "100%" }} />
    </div>
  );
}

export default CustomOverlaysPage;
