// frameworks/angular/TS/src/app/pages/home-page/home-page.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";
import { AngularLogoComponent } from "../../components/logos/angular-logo.component";
import { NutrientLogoComponent } from "../../components/logos/nutrient-logo.component";

interface Example {
  path: string;
  title: string;
  description: string;
  features: string[];
}

@Component({
  selector: "app-home-page",
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    NutrientLogoComponent,
    AngularLogoComponent,
  ],
  template: `
    <div class="homepage">
      <div class="homepage-container">
        <header class="homepage-header">
          <div class="homepage-tech-stack">
            <div class="tech-item">
              <a
                href="https://www.nutrient.io"
                target="_blank"
                rel="noopener noreferrer"
                class="link-no-style"
              >
                <app-nutrient-logo></app-nutrient-logo>
              </a>
            </div>
            <div class="tech-plus">+</div>
            <div class="tech-item">
              <a
                href="https://angular.dev/"
                target="_blank"
                rel="noopener noreferrer"
                class="link-no-style"
              >
                <app-angular-logo></app-angular-logo>
              </a>
            </div>
          </div>
          <p class="homepage-subtitle">Select an example to get started</p>
        </header>

        <div class="examples-grid">
          <div *ngFor="let example of examples" class="example-card">
            <h3 class="example-title">{{ example.title }}</h3>
            <p class="example-description">{{ example.description }}</p>

            <h4 class="features-title">Features:</h4>
            <ul class="features-list">
              <li *ngFor="let feature of example.features">{{ feature }}</li>
            </ul>

            <div class="button-container">
              <a [routerLink]="example.path" class="view-button"> View </a>
            </div>
          </div>
        </div>

        <footer class="homepage-footer">
          <p>
            Learn more:
            <a
              href="https://www.nutrient.io/guides/web/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Nutrient Web SDK Documentation
            </a>
          </p>
        </footer>
      </div>
    </div>
  `,
  styleUrls: ["./home-page.component.css"],
})
export class HomePageComponent {
  examples: Example[] = [
    {
      path: "/basic-viewer",
      title: "Basic Viewer",
      description: "Simple PDF document loading with basic controls",
      features: ["Document loading", "Zoom controls", "Page navigation"],
    },
    {
      path: "/magazine-mode",
      title: "Magazine Mode",
      description: "Advanced magazine-style reader with custom features",
      features: [
        "Double-page layout",
        "Custom toolbar",
        "Fullscreen support",
        "iOS optimization",
      ],
    },
    {
      path: "/custom-overlays",
      title: "Custom Overlays",
      description: "Interactive overlays that appear on page clicks",
      features: [
        "Page click events",
        "HTML overlay content",
        "Dynamic positioning",
        "Video embedding",
      ],
    },
    {
      path: "/watermarks",
      title: "Watermarks",
      description: "Add watermarks to PDFs using JavaScript",
      features: [
        "Custom watermark text",
        "Watermark rotation",
        "Transparency control",
        "Print integration",
      ],
    },
  ];
}

// frameworks/react/JS/src/pages/HomePage.jsx
import { Link } from "react-router-dom";
import "./HomePage.css";
import { NutrientLogo } from "../components/logos/NutrientLogo";
import ReactLogo from "../components/logos/ReactLogo";

function HomePage() {
  const examples = [
    {
      path: "/basic-viewer",
      title: "Basic Viewer",
      description: "Simple PDF document loading with basic controls",
      features: ["Document loading", "Zoom controls", "Page navigation"],
    },
    {
      path: "/magazine-mode",
      title: "Magazine Mode",
      description: "Advanced magazine-style reader with custom features",
      features: [
        "Double-page layout",
        "Custom toolbar",
        "Fullscreen support",
        "iOS optimization",
      ],
    },
    {
      path: "/custom-overlays",
      title: "Custom Overlays",
      description: "Interactive overlays that appear on page clicks",
      features: [
        "Page click events",
        "HTML overlay content",
        "Dynamic positioning",
        "Video embedding",
      ],
    },
    {
      path: "/watermarks",
      title: "Watermarks",
      description: "Add watermarks to PDFs using JavaScript",
      features: [
        "Custom watermark text",
        "Watermark rotation",
        "Transparency control",
        "Print integration",
      ],
    },
  ];

  return (
    <div className="homepage">
      <div className="homepage-container">
        <header className="homepage-header">
          <div className="homepage-tech-stack">
            <div className="tech-item">
              <Link
                to="https://www.nutrient.io"
                target="_blank"
                rel="noopener noreferrer"
                className="link-no-style"
              >
                <NutrientLogo />
              </Link>
            </div>
            <div className="tech-plus">+</div>
            <div className="tech-item">
              <Link
                to="https://react.dev/"
                target="_blank"
                rel="noopener noreferrer"
                className="link-no-style"
              >
                <ReactLogo />
              </Link>
            </div>
          </div>
          <p className="homepage-subtitle">Select an example to get started</p>
        </header>

        <div className="examples-grid">
          {examples.map((example) => (
            <div key={example.path} className="example-card">
              <h3 className="example-title">{example.title}</h3>
              <p className="example-description">{example.description}</p>

              <h4 className="features-title">Features:</h4>
              <ul className="features-list">
                {example.features.map((feature) => (
                  <li key={feature}>{feature}</li>
                ))}
              </ul>

              <div className="button-container">
                <Link to={example.path} className="view-button">
                  View
                </Link>
              </div>
            </div>
          ))}
        </div>

        <footer className="homepage-footer">
          <p>
            Learn more:{" "}
            <a
              href="https://www.nutrient.io/guides/web/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Nutrient Web SDK Documentation
            </a>
          </p>
        </footer>
      </div>
    </div>
  );
}

export default HomePage;
