// examples/react/src/components/PdfViewer.tsx
import type * as Nutrient from "@nutrient-sdk/viewer";
import { useEffect, useRef } from "react";

interface PdfViewerProps {
  document: string;
}

export default function PdfViewer({ document }: PdfViewerProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<Nutrient.Instance | null>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container || !window.NutrientViewer) return;

    window.NutrientViewer.load({
      container,
      document,
      useCDN: true,
    }).then((instance) => {
      instanceRef.current = instance;
    });

    return () => {
      if (container) {
        window.NutrientViewer?.unload(container);
      }
    };
  }, [document]);

  return (
    <div
      ref={containerRef}
      style={{ width: "100%", height: "100%", position: "relative" }}
    />
  );
}

// examples/svelte/src/lib/PdfViewer.svelte
<script lang="ts">
import type * as Nutrient from "@nutrient-sdk/viewer";
import { onDestroy, onMount } from "svelte";

interface Props {
  document: string;
}

const { document }: Props = $props();
let container: HTMLDivElement;
let instance: Nutrient.Instance | null = null;
let currentDocument = "";

async function loadDocument(doc: string) {
  if (!container || !window.NutrientViewer || doc === currentDocument) return;

  if (instance) {
    window.NutrientViewer.unload(container);
    instance = null;
  }

  currentDocument = doc;
  instance = await window.NutrientViewer.load({
    container,
    document: doc,
    useCDN: true,
  });
}

onMount(() => {
  loadDocument(document);
});

$effect(() => {
  // Only react to document changes after initial mount
  if (container && document && document !== currentDocument) {
    loadDocument(document);
  }
});

onDestroy(() => {
  if (container && instance) {
    window.NutrientViewer?.unload(container);
  }
});
</script>

<div bind:this={container} class="pdf-container"></div>

<style>
  .pdf-container {
    height: 100%;
    width: 100%;
    position: relative;
  }
</style>
