// frameworks/react/TS/src/pages/BasicViewerPage.tsx
import { useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import {
  loadBasicViewer,
  unloadBasicViewer,
} from "../nutrient/basic-viewer/implementation";
import { loadNutrientViewer } from "../nutrient/loadNutrientViewer";
import "./BasicViewerPage.css";

function BasicViewerPage() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;

    if (!container) return;

    let nutrientViewer: Awaited<ReturnType<typeof loadNutrientViewer>> | null =
      null;

    (async () => {
      nutrientViewer = await loadNutrientViewer();

      if (container && nutrientViewer) {
        unloadBasicViewer(nutrientViewer, container);

        loadBasicViewer(nutrientViewer, container);
      }
    })();

    return () => {
      if (nutrientViewer && container) {
        unloadBasicViewer(nutrientViewer, container);
      }
    };
  }, []);

  return (
    <div className="basic-viewer-container">
      <nav className="basic-viewer-nav">
        <Link to="/" className="basic-viewer-back-link">
          ← Back to Examples
        </Link>
        <h2 className="basic-viewer-title">Basic Viewer</h2>
        <span className="basic-viewer-subtitle">
          Simple PDF viewing with standard controls
        </span>
      </nav>

      <div ref={containerRef} className="basic-viewer-content" />
    </div>
  );
}

export default BasicViewerPage;

// frameworks/solid/ts/src/pages/BasicViewerPage.tsx
import type NutrientViewer from "@nutrient-sdk/viewer";
import { A } from "@solidjs/router";
import { onCleanup, onMount } from "solid-js";
import {
  loadBasicViewer,
  unloadBasicViewer,
} from "../nutrient/basic-viewer/implementation";
import { loadNutrientViewer } from "../nutrient/loadNutrientViewer";
import "./BasicViewerPage.css";

function BasicViewerPage() {
  let containerRef: HTMLDivElement | undefined;
  let nutrientViewer: typeof NutrientViewer | null = null;

  onMount(async () => {
    if (!containerRef) return;

    nutrientViewer = await loadNutrientViewer();

    if (containerRef && nutrientViewer) {
      unloadBasicViewer(nutrientViewer, containerRef);
      loadBasicViewer(nutrientViewer, containerRef);
    }
  });

  onCleanup(() => {
    if (nutrientViewer && containerRef) {
      unloadBasicViewer(nutrientViewer, containerRef);
    }
  });

  return (
    <div class="basic-viewer-container">
      <nav class="basic-viewer-nav">
        <A href="/" class="basic-viewer-back-link">
          ← Back to Examples
        </A>
        <h2 class="basic-viewer-title">Basic Viewer</h2>
        <span class="basic-viewer-subtitle">
          Simple PDF viewing with standard controls
        </span>
      </nav>

      <div ref={containerRef} class="basic-viewer-content" />
    </div>
  );
}

export default BasicViewerPage;
