// frameworks/angular/TS/src/app/pages/custom-overlays-page/custom-overlays-page.component.ts
import {
  type AfterViewInit,
  Component,
  type ElementRef,
  type OnDestroy,
  ViewChild,
} from "@angular/core";
import { RouterLink } from "@angular/router";
import { loadCustomOverlaysViewer } from "../../../examples/custom-overlays/implementation";
import { loadNutrientViewer } from "../../utils/loadNutrientViewer";

@Component({
  selector: "app-custom-overlays-page",
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="custom-overlays-container">
      <nav class="custom-overlays-nav">
        <a routerLink="/" class="custom-overlays-back-link">
          ← Back to Examples
        </a>
        <h2 class="custom-overlays-title">Custom Overlays</h2>
        <span class="custom-overlays-subtitle">
          Interactive overlays that appear on page clicks
        </span>
      </nav>

      <div #container class="custom-overlays-content"></div>
    </div>
  `,
  styleUrls: ["./custom-overlays-page.component.css"],
})
export class CustomOverlaysPageComponent implements AfterViewInit, OnDestroy {
  @ViewChild("container", { static: true }) containerRef!: ElementRef;

  private nutrientViewer: ReturnType<typeof loadNutrientViewer>;

  async ngAfterViewInit() {
    const container = this.containerRef.nativeElement;
    if (!container) return;

    try {
      this.nutrientViewer = await loadNutrientViewer();

      // Unload any existing instance
      this.nutrientViewer.unload(container);

      await loadCustomOverlaysViewer(this.nutrientViewer, container);
    } catch (error) {
      console.error("Failed to load Nutrient Viewer:", error);
    }
  }

  ngOnDestroy() {
    if (this.nutrientViewer && this.containerRef?.nativeElement) {
      this.nutrientViewer.unload(this.containerRef.nativeElement);
    }
  }
}

// frameworks/solid/ts/src/pages/CustomOverlaysPage.tsx
import type NutrientViewer from "@nutrient-sdk/viewer";
import { A } from "@solidjs/router";
import { onCleanup, onMount } from "solid-js";
import {
  loadCustomOverlaysViewer,
  unloadCustomOverlaysViewer,
} from "../nutrient/custom-overlays/implementation";
import { loadNutrientViewer } from "../nutrient/loadNutrientViewer";
import "./BasicViewerPage.css";

function CustomOverlaysPage() {
  let containerRef: HTMLDivElement | undefined;
  let nutrientViewer: typeof NutrientViewer | null = null;

  onMount(async () => {
    if (!containerRef) return;

    nutrientViewer = await loadNutrientViewer();

    if (containerRef && nutrientViewer) {
      unloadCustomOverlaysViewer(nutrientViewer, containerRef);
      loadCustomOverlaysViewer(nutrientViewer, containerRef);
    }
  });

  onCleanup(() => {
    if (nutrientViewer && containerRef) {
      unloadCustomOverlaysViewer(nutrientViewer, containerRef);
    }
  });

  return (
    <div class="basic-viewer-container">
      <nav class="basic-viewer-nav">
        <A href="/" class="basic-viewer-back-link">
          ← Back to Examples
        </A>
        <h2 class="basic-viewer-title">Custom Overlays</h2>
        <span class="basic-viewer-subtitle">
          Interactive overlays that appear on page clicks
        </span>
      </nav>

      <div ref={containerRef} class="basic-viewer-content" />
    </div>
  );
}

export default CustomOverlaysPage;
