// frameworks/nuxt/TS/pages/magazine-mode.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import {
  loadMagazineViewer,
  unloadMagazineViewer,
} from "../examples/magazine-mode/implementation";
import { loadNutrientViewer } from "../utils/loadNutrientViewer";

const containerRef = ref<HTMLDivElement | null>(null);

onMounted(() => {
  const container = containerRef.value;

  if (!container) return;

  let nutrientViewer: ReturnType<typeof loadNutrientViewer>;

  try {
    nutrientViewer = loadNutrientViewer();

    nutrientViewer.unload(container);

    loadMagazineViewer(nutrientViewer, container);
  } catch (error) {
    console.error("Failed to load Nutrient Viewer:", error);
  }

  return () => {
    if (nutrientViewer && container) {
      unloadMagazineViewer(nutrientViewer, container);
    }
  };
});

onUnmounted(() => {
  const container = containerRef.value;
  const { NutrientViewer } = window;

  if (container && NutrientViewer) {
    unloadMagazineViewer(NutrientViewer, container);
  }
});
</script>

<template>
  <div :style="{ height: '100vh', display: 'flex', flexDirection: 'column' }">
    <nav
      :style="{
        padding: '1rem',
        backgroundColor: '#f5f5f5',
        borderBottom: '1px solid #ddd',
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
      }"
    >
      <router-link
        to="/"
        :style="{
          textDecoration: 'none',
          color: '#4A8FED',
          fontSize: '0.9rem',
        }"
      >
        ← Back to Examples
      </router-link>
      <h2 :style="{ margin: 0, fontSize: '1.1rem' }">Magazine Mode</h2>
      <span :style="{ fontSize: '0.9rem', color: '#666' }">
        Double-page layout with custom toolbar and fullscreen support
      </span>
    </nav>

    <div ref="containerRef" :style="{ flex: 1, width: '100%' }" />
  </div>
</template>

// frameworks/next/JS/app/magazine-mode/page.jsx
"use client";

import Link from "next/link";
import { useEffect, useRef } from "react";
import {
  loadMagazineViewer,
  unloadMagazineViewer,
} from "../../examples/magazine-mode/implementation";
import { loadNutrientViewer } from "../utils/loadNutrientViewer";

function MagazineModePage() {
  const containerRef = useRef(null);

  useEffect(() => {
    const container = containerRef.current;

    if (!container) return;

    let nutrientViewer;

    try {
      nutrientViewer = loadNutrientViewer();

      nutrientViewer.unload(container);

      loadMagazineViewer(nutrientViewer, container);
    } catch (error) {
      console.error("Failed to load Nutrient Viewer:", error);
    }

    return () => {
      if (nutrientViewer && container) {
        unloadMagazineViewer(nutrientViewer, container);
      }
    };
  }, []);

  return (
    <div style={{ height: "100vh", display: "flex", flexDirection: "column" }}>
      <nav
        style={{
          padding: "1rem",
          backgroundColor: "#f5f5f5",
          borderBottom: "1px solid #ddd",
          display: "flex",
          alignItems: "center",
          gap: "1rem",
        }}
      >
        <Link
          href="/"
          style={{
            textDecoration: "none",
            color: "#4A8FED",
            fontSize: "0.9rem",
          }}
        >
          ← Back to Examples
        </Link>
        <h2 style={{ margin: 0, fontSize: "1.1rem" }}>Magazine Mode</h2>
        <span style={{ fontSize: "0.9rem", color: "#666" }}>
          Double-page layout with custom toolbar and fullscreen support
        </span>
      </nav>

      <div ref={containerRef} style={{ flex: 1, width: "100%" }} />
    </div>
  );
}

export default MagazineModePage;
