// examples/svelte/src/PdfViewerComponent.svelte
<script>
import PSPDFKit from "@nutrient-sdk/viewer";
import { afterUpdate, onDestroy, onMount } from "svelte";

let currentDocument;
let container;
let instance;

export let document;

async function load() {
  currentDocument = document;
  instance = await PSPDFKit.load({
    baseUrl: `${window.location.protocol}//${window.location.host}/`,
    container: container,
    document: document,
  });
}

function unload() {
  PSPDFKit.unload(instance);
  instance = null;
}

onMount(() => {
  load();
});

afterUpdate(() => {
  if (document !== currentDocument) {
    unload();
    load();
  }
});

onDestroy(() => {
  unload();
});
</script>

<body>
  <div bind:this={container} style="height: 100vh; width: 100vw;" />
</body>

// examples/react/src/components/PdfViewerComponent.js
import { useEffect, useRef } from "react";

export default function PdfViewerComponent(props) {
  const containerRef = useRef(null);

  useEffect(() => {
    const container = containerRef.current;
    let PSPDFKit;

    (async () => {
      PSPDFKit = await import("@nutrient-sdk/viewer");
      await PSPDFKit.load({
        // Container where PSPDFKit should be mounted.
        container,
        // The document to open.
        document: props.document,
        // Use the public directory URL as a base URL. PSPDFKit will download its library assets from here.
        baseUrl: `${window.location.protocol}//${window.location.host}/${process.env.PUBLIC_URL}`,
      });
    })();

    return () => PSPDFKit?.unload(container);
  }, [props.document]);

  return <div ref={containerRef} style={{ width: "100%", height: "100vh" }} />;
}
