// examples/svelte/src/PdfViewerComponent.svelte
<script>
import NutrientViewer from "@nutrient-sdk/viewer";
import { afterUpdate, onDestroy, onMount } from "svelte";

let currentDocument;
let container;
let instance;

export let document;

async function load() {
  currentDocument = document;
  instance = await NutrientViewer.load({
    baseUrl: `${window.location.protocol}//${window.location.host}/`,
    container: container,
    document: document,
  });
}

function unload() {
  NutrientViewer.unload(instance);
  instance = null;
}

onMount(() => {
  load();
});

afterUpdate(() => {
  if (document !== currentDocument) {
    unload();
    load();
  }
});

onDestroy(() => {
  unload();
});
</script>

<body>
  <div bind:this={container} style="height: 100vh; width: 100vw;" />
</body>

// examples/react/src/components/PdfViewerComponent.jsx
import { useEffect, useRef } from "react";

export default function PdfViewerComponent(props) {
  const containerRef = useRef(null);

  useEffect(() => {
    const container = containerRef.current;
    let NutrientViewer;

    (async () => {
      NutrientViewer = await import("@nutrient-sdk/viewer");
      await NutrientViewer.load({
        // Container where Nutrient should be mounted.
        container,
        // The document to open.
        document: props.document,
        // Use the public directory URL as a base URL. Nutrient will download its library assets from here.
        baseUrl: `${window.location.protocol}//${window.location.host}/nutrient-viewer-lib/`,
      });
    })();

    return () => NutrientViewer?.unload(container);
  }, [props.document]);

  return <div ref={containerRef} style={{ width: "100%", height: "100vh" }} />;
}
