// frameworks/nuxt/JS/pages/magazine-mode.vue
<template>
  <div :style="{ height: '100vh', display: 'flex', flexDirection: 'column' }">
    <nav :style="{
      padding: '1rem',
      backgroundColor: '#f5f5f5',
      borderBottom: '1px solid #ddd',
      display: 'flex',
      alignItems: 'center',
      gap: '1rem'
    }">
      <NuxtLink
        to="/"
        :style="{
          textDecoration: 'none',
          color: '#4A8FED',
          fontSize: '0.9rem'
        }"
      >
        ← Back to Examples
      </NuxtLink>
      <h2 :style="{ margin: 0, fontSize: '1.1rem' }">Magazine Mode</h2>
      <span :style="{ fontSize: '0.9rem', color: '#666' }">
        Double-page layout with custom toolbar and fullscreen support
      </span>
    </nav>
    
    <div ref="containerRef" :style="{ flex: 1, width: '100%' }" />
  </div>
</template>

<script setup>
import {
  loadMagazineViewer,
  unloadMagazineViewer,
} from "../../examples/js/magazine-mode/implementation.js";

const containerRef = ref(null);

onMounted(async () => {
  // Wait for NutrientViewer to be available
  while (!window.NutrientViewer) {
    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  const container = containerRef.value;
  const { NutrientViewer } = window;

  if (container && NutrientViewer) {
    loadMagazineViewer(NutrientViewer, container);
  }
});

onUnmounted(() => {
  const container = containerRef.value;
  const { NutrientViewer } = window;

  if (container && NutrientViewer) {
    unloadMagazineViewer(NutrientViewer, container);
  }
});
</script>

// frameworks/nextjs/JS/app/magazine-mode/page.jsx
'use client';

import { useEffect, useRef } from 'react';
import Link from 'next/link';
import { loadMagazineViewer, unloadMagazineViewer } from '../../../examples/js/magazine-mode/implementation.js';

export default function MagazineModePage() {
  const containerRef = useRef(null);

  useEffect(() => {
    const container = containerRef.current;
    const { NutrientViewer } = window;
    
    if (container && NutrientViewer) {
      loadMagazineViewer(NutrientViewer, container);
    }

    return () => {
      if (NutrientViewer) {
        unloadMagazineViewer(NutrientViewer, container);
      }
    };
  }, []);

  return (
    <div style={{ height: '100vh', display: 'flex', flexDirection: 'column' }}>
      <nav style={{ 
        padding: '1rem', 
        backgroundColor: '#f5f5f5', 
        borderBottom: '1px solid #ddd',
        display: 'flex',
        alignItems: 'center',
        gap: '1rem'
      }}>
        <Link 
          href="/"
          style={{
            textDecoration: 'none',
            color: '#4A8FED',
            fontSize: '0.9rem'
          }}
        >
          ← Back to Examples
        </Link>
        <h2 style={{ margin: 0, fontSize: '1.1rem' }}>Magazine Mode</h2>
        <span style={{ fontSize: '0.9rem', color: '#666' }}>
          Double-page layout with custom toolbar and fullscreen support
        </span>
      </nav>
      
      <div ref={containerRef} style={{ flex: 1, width: '100%' }} />
    </div>
  );
}
