// examples/react/src/components/PdfViewer.tsx
import type * as Nutrient from "@nutrient-sdk/viewer";
import { useEffect, useRef } from "react";

interface PdfViewerProps {
  document: string;
}

export default function PdfViewer({ document }: PdfViewerProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<Nutrient.Instance | null>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container || !window.NutrientViewer) return;

    window.NutrientViewer.load({
      container,
      document,
      useCDN: true,
    }).then((instance) => {
      instanceRef.current = instance;
    });

    return () => {
      if (container) {
        window.NutrientViewer?.unload(container);
      }
    };
  }, [document]);

  return (
    <div
      ref={containerRef}
      style={{ width: "100%", height: "100%", position: "relative" }}
    />
  );
}

// examples/svelte/src/PdfViewerComponent.svelte
<script>
import NutrientViewer from "@nutrient-sdk/viewer";
import { afterUpdate, onDestroy, onMount } from "svelte";

let currentDocument;
let container;
let instance;

export let document;

async function load() {
  currentDocument = document;
  instance = await NutrientViewer.load({
    baseUrl: `${window.location.protocol}//${window.location.host}/`,
    container: container,
    document: document,
  });
}

function unload() {
  NutrientViewer.unload(instance);
  instance = null;
}

onMount(() => {
  load();
});

afterUpdate(() => {
  if (document !== currentDocument) {
    unload();
    load();
  }
});

onDestroy(() => {
  unload();
});
</script>

<body>
  <div bind:this={container} style="height: 100vh; width: 100vw;" />
</body>
